//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderTrackingSystem.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrderTrackingSystem.Logic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mieszkanie.
        /// </summary>
        public static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nabywca.
        /// </summary>
        public static string Buyer {
            get {
                return ResourceManager.GetString("Buyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojemność.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł.
        /// </summary>
        public static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasto.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezygnacja.
        /// </summary>
        public static string Complaint {
            get {
                return ResourceManager.GetString("Complaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozwiązanie reklamacji.
        /// </summary>
        public static string ComplaintResolved {
            get {
                return ResourceManager.GetString("ComplaintResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reklamacja została pomyślnie rozwiązana, przesyłka jest w drodze.
        /// </summary>
        public static string ComplaintResolvedDesc {
            get {
                return ResourceManager.GetString("ComplaintResolvedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witam, zaakceptowałem reklamacje dotyczącą zamówienia {0}. Proszę o zamknięcie reklamacji. Pozdrawiam {1}..
        /// </summary>
        public static string ComplaintResolvedTemplate {
            get {
                return ResourceManager.GetString("ComplaintResolvedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Założona reklamacja.
        /// </summary>
        public static string ComplaintSet {
            get {
                return ResourceManager.GetString("ComplaintSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestrowana reklamacja nabywcy.
        /// </summary>
        public static string ComplaintSetDesc {
            get {
                return ResourceManager.GetString("ComplaintSetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestrowana nowa reklamacja.
        /// </summary>
        public static string ComplaintSetHeader {
            get {
                return ResourceManager.GetString("ComplaintSetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reklamacja została zaakceptowana [AUTOMATYCZNA].
        /// </summary>
        public static string ComplaintWasResolved {
            get {
                return ResourceManager.GetString("ComplaintWasResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treść.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data utworzenia.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data utworzenia.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dni do odbioru.
        /// </summary>
        public static string DaysToGet {
            get {
                return ResourceManager.GetString("DaysToGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ dostawy.
        /// </summary>
        public static string DeliveryType {
            get {
                return ResourceManager.GetString("DeliveryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabat.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przyjęta w lokalnym oddziale.
        /// </summary>
        public static string GetByLocal {
            get {
                return ResourceManager.GetString("GetByLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesyłka trafiła do lokalnego centrum procesingowo.
        /// </summary>
        public static string GetByLocalDesc {
            get {
                return ResourceManager.GetString("GetByLocalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odebrana od nadawcy.
        /// </summary>
        public static string GetFromSeller {
            get {
                return ResourceManager.GetString("GetFromSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesyłka została odebrana od nadawcy.
        /// </summary>
        public static string GetFromSellerDesc {
            get {
                return ResourceManager.GetString("GetFromSellerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odebrana.
        /// </summary>
        public static string Getted {
            get {
                return ResourceManager.GetString("Getted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odebrana.
        /// </summary>
        public static string GettedDesc {
            get {
                return ResourceManager.GetString("GettedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budynek.
        /// </summary>
        public static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrazek.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witam, złożyłem reklamację na swoje zamówienie pod numerem {0}. Treść: {1}. Pozdrawiam {2}..
        /// </summary>
        public static string MailAutomaticSetComplaint {
            get {
                return ResourceManager.GetString("MailAutomaticSetComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestrowana przesyłka dla Ciebie [AUTOMATYCZNA].
        /// </summary>
        public static string MailCaptionAfterSendAutomatic {
            get {
                return ResourceManager.GetString("MailCaptionAfterSendAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witam, wysłałem do Ciebie przesyłke, jej numer {0}. Pozdrawiam. {1}.
        /// </summary>
        public static string MailContentAfterSendAutomatic {
            get {
                return ResourceManager.GetString("MailContentAfterSendAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netto.
        /// </summary>
        public static string Netto {
            get {
                return ResourceManager.GetString("Netto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamówienie.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ opłaty.
        /// </summary>
        public static string PayType {
            get {
                return ResourceManager.GetString("PayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesyłka jest przygotowywana przez producenta.
        /// </summary>
        public static string PrepareBySellerDesc {
            get {
                return ResourceManager.GetString("PrepareBySellerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przygotowanie przesyłki.
        /// </summary>
        public static string PrepatedBySeller {
            get {
                return ResourceManager.GetString("PrepatedBySeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gotowa do odbioru.
        /// </summary>
        public static string ReadyToPickup {
            get {
                return ResourceManager.GetString("ReadyToPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesyłka jest gotowa do odbioru.
        /// </summary>
        public static string ReadyToPickupDesc {
            get {
                return ResourceManager.GetString("ReadyToPickupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odbiorca.
        /// </summary>
        public static string Receiver {
            get {
                return ResourceManager.GetString("Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dni na rozpatrywanie.
        /// </summary>
        public static string RemainDays {
            get {
                return ResourceManager.GetString("RemainDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwrot do nadawcy.
        /// </summary>
        public static string ReturnToSeller {
            get {
                return ResourceManager.GetString("ReturnToSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesyłka została zwrócona do nadawcy.
        /// </summary>
        public static string ReturnToSellerDesc {
            get {
                return ResourceManager.GetString("ReturnToSellerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprzedawca.
        /// </summary>
        public static string Seller {
            get {
                return ResourceManager.GetString("Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wysyłki.
        /// </summary>
        public static string SendDate {
            get {
                return ResourceManager.GetString("SendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadawca.
        /// </summary>
        public static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysłana z lokalnego oddziału.
        /// </summary>
        public static string SentFromLocal {
            get {
                return ResourceManager.GetString("SentFromLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesyłka została wysłana z lokalnego centrum.
        /// </summary>
        public static string SentFromLocalDesc {
            get {
                return ResourceManager.GetString("SentFromLocalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sklep.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydana do doręczenia.
        /// </summary>
        public static string ToDelivery {
            get {
                return ResourceManager.GetString("ToDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesyłka jest przekazana do doręczenia.
        /// </summary>
        public static string ToDeliveryDesc {
            get {
                return ResourceManager.GetString("ToDeliveryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string UniqueName {
            get {
                return ResourceManager.GetString("UniqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        public static string VAT {
            get {
                return ResourceManager.GetString("VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas pracy.
        /// </summary>
        public static string WorkTime {
            get {
                return ResourceManager.GetString("WorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pocztowy.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
