//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderTrackingSystem.Logic.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintRelations
    {
        public int ComplaintId { get; set; }
        public int ComplaintFolderId { get; set; }
        public int Id { get; set; }
    
        public virtual ComplaintDefinitions ComplaintDefinitions { get; set; }
        public virtual ComplaintFolders ComplaintFolders { get; set; }
    }
}
