//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderTrackingSystem.Logic.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrderTrackingSystemEntities : DbContext
    {
        public OrderTrackingSystemEntities()
            : base("name=OrderTrackingSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Localizations> Localizations { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrderStates> OrderStates { get; set; }
        public virtual DbSet<Pickups> Pickups { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Sellers> Sellers { get; set; }
        public virtual DbSet<Sells> Sells { get; set; }
        public virtual DbSet<Carts> Carts { get; set; }
        public virtual DbSet<LocalizationRow> LocalizationRow { get; set; }
    }
}
