//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderTrackingSystem.Logic.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrderCarts = new HashSet<OrderCarts>();
            this.SellCarts = new HashSet<SellCarts>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal PriceNetto { get; set; }
        public byte VAT { get; set; }
        public decimal PriceBrutto { get; set; }
        public int Category { get; set; }
        public decimal Weight { get; set; }
        public byte Discount { get; set; }
        public int SellerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCarts> OrderCarts { get; set; }
        public virtual Sellers Sellers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellCarts> SellCarts { get; set; }
    }
}
