//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderTrackingSystem.Logic.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellCarts
    {
        public int ProductId { get; set; }
        public byte Amount { get; set; }
        public int SellId { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Sells Sells { get; set; }
    }
}
