//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderTrackingSystem.Logic.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vouchers
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public decimal Value { get; set; }
        public decimal RemainValue { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
