//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderTrackingSystem.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrderTrackingSystem.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdź.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opłać całe zamówienie.
        /// </summary>
        public static string AcceptFullVoucher {
            get {
                return ResourceManager.GetString("AcceptFullVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły konta.
        /// </summary>
        public static string AccountDetails {
            get {
                return ResourceManager.GetString("AccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj klientów.
        /// </summary>
        public static string AddClients {
            get {
                return ResourceManager.GetString("AddClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj wzorzec.
        /// </summary>
        public static string AddComplaint {
            get {
                return ResourceManager.GetString("AddComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj wzorzec do folderu.
        /// </summary>
        public static string AddComplaintToFolder {
            get {
                return ResourceManager.GetString("AddComplaintToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj folder.
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj procedurę do bazy.
        /// </summary>
        public static string AddProcedureToDB {
            get {
                return ResourceManager.GetString("AddProcedureToDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj produkt.
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj produkt.
        /// </summary>
        public static string AddProductAction {
            get {
                return ResourceManager.GetString("AddProductAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj do koszyka.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiek.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota: .
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota odliczalna.
        /// </summary>
        public static string AmountToMinus {
            get {
                return ResourceManager.GetString("AmountToMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaakceptuj reklamację.
        /// </summary>
        public static string ApproveComplaint {
            get {
                return ResourceManager.GetString("ApproveComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatyczne procesy.
        /// </summary>
        public static string AutoProcesses {
            get {
                return ResourceManager.GetString("AutoProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostępne punkty odbiory.
        /// </summary>
        public static string AvailablePickups {
            get {
                return ResourceManager.GetString("AvailablePickups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkty dostępne.
        /// </summary>
        public static string AvailableProducts {
            get {
                return ResourceManager.GetString("AvailableProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opakowanie.
        /// </summary>
        public static string BoxPrice {
            get {
                return ResourceManager.GetString("BoxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota brutto.
        /// </summary>
        public static string Brutto {
            get {
                return ResourceManager.GetString("Brutto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Możliwość zaznaczenia kilku na raz i uruchomienie.
        /// </summary>
        public static string CanSelectManyAndRun {
            get {
                return ResourceManager.GetString("CanSelectManyAndRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koszyk.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień status przesyłki.
        /// </summary>
        public static string ChangeParcelState {
            get {
                return ResourceManager.GetString("ChangeParcelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień status.
        /// </summary>
        public static string ChangeState {
            get {
                return ResourceManager.GetString("ChangeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz szablon reklamacyjny.
        /// </summary>
        public static string ChooseComplaintTemplate {
            get {
                return ResourceManager.GetString("ChooseComplaintTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść koszyk.
        /// </summary>
        public static string ClearCart {
            get {
                return ResourceManager.GetString("ClearCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reklamacje klientów.
        /// </summary>
        public static string ClientsComplaints {
            get {
                return ResourceManager.GetString("ClientsComplaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamówienia klientów.
        /// </summary>
        public static string ClientsOrders {
            get {
                return ResourceManager.GetString("ClientsOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres firmy.
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reklamacje klientów.
        /// </summary>
        public static string CompanyComplaints {
            get {
                return ResourceManager.GetString("CompanyComplaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły firmy.
        /// </summary>
        public static string CompanyDetails {
            get {
                return ResourceManager.GetString("CompanyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamówienia klientów.
        /// </summary>
        public static string CompanyOrders {
            get {
                return ResourceManager.GetString("CompanyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezygnacja.
        /// </summary>
        public static string Complaint {
            get {
                return ResourceManager.GetString("Complaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość dni na rozpatrywanie.
        /// </summary>
        public static string ComplaintDays {
            get {
                return ResourceManager.GetString("ComplaintDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decyzja sprzedawcy.
        /// </summary>
        public static string ComplaintDecision {
            get {
                return ResourceManager.GetString("ComplaintDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreator definicji wzorca.
        /// </summary>
        public static string ComplaintDefinitionCreator {
            get {
                return ResourceManager.GetString("ComplaintDefinitionCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foldery reklamacyjne.
        /// </summary>
        public static string ComplaintFolders {
            get {
                return ResourceManager.GetString("ComplaintFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa wzorca.
        /// </summary>
        public static string ComplaintName {
            get {
                return ResourceManager.GetString("ComplaintName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wzorce reklamacyjne.
        /// </summary>
        public static string ComplaintObject {
            get {
                return ResourceManager.GetString("ComplaintObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przebieg reklamacji.
        /// </summary>
        public static string ComplaintProcess {
            get {
                return ResourceManager.GetString("ComplaintProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Założenie reklamacji.
        /// </summary>
        public static string ComplaintRegister {
            get {
                return ResourceManager.GetString("ComplaintRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koniec reklamacji.
        /// </summary>
        public static string ComplaintResolve {
            get {
                return ResourceManager.GetString("ComplaintResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestrowana nowa reklamacja.
        /// </summary>
        public static string ComplaintSetHeader {
            get {
                return ResourceManager.GetString("ComplaintSetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wzorce reklamacyjne.
        /// </summary>
        public static string ComplaintViews {
            get {
                return ResourceManager.GetString("ComplaintViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reklamacja została zaakceptowana [AUTOMATYCZNA].
        /// </summary>
        public static string ComplaintWasResolved {
            get {
                return ResourceManager.GetString("ComplaintWasResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguracja.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź odbiór.
        /// </summary>
        public static string ConfirmReceive {
            get {
                return ResourceManager.GetString("ConfirmReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treść.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz wzorzec.
        /// </summary>
        public static string CreateComplaint {
            get {
                return ResourceManager.GetString("CreateComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres zamieszkania.
        /// </summary>
        public static string CustomerAddress {
            get {
                return ResourceManager.GetString("CustomerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostawa.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkt odbioru.
        /// </summary>
        public static string DeliveryPoint {
            get {
                return ResourceManager.GetString("DeliveryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metody dostawy.
        /// </summary>
        public static string DeliveryType {
            get {
                return ResourceManager.GetString("DeliveryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulpit.
        /// </summary>
        public static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyłącz Fullscreen.
        /// </summary>
        public static string DisableFullscreen {
            get {
                return ResourceManager.GetString("DisableFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zniżka.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skrzynka E-MAIL.
        /// </summary>
        public static string Emailbox {
            get {
                return ResourceManager.GetString("Emailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Włącz Fullscreen.
        /// </summary>
        public static string EnableFullscreen {
            get {
                return ResourceManager.GetString("EnableFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyjdź.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data ważności: {0:dd/MM/yyyy}.
        /// </summary>
        public static string ExpireDate {
            get {
                return ResourceManager.GetString("ExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data ważności: .
        /// </summary>
        public static string ExpireDateStr {
            get {
                return ResourceManager.GetString("ExpireDateStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odfiltruj.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukaj zamówienie/wysyłkę.
        /// </summary>
        public static string FindOrderOrSell {
            get {
                return ResourceManager.GetString("FindOrderOrSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukaj odbiorcę.
        /// </summary>
        public static string FindReceiver {
            get {
                return ResourceManager.GetString("FindReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukaj sklep.
        /// </summary>
        public static string FindShop {
            get {
                return ResourceManager.GetString("FindShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa folderu.
        /// </summary>
        public static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunięcie folderu.
        /// </summary>
        public static string FolderRemoving {
            get {
                return ResourceManager.GetString("FolderRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygeneruj automatyczną wiadomość.
        /// </summary>
        public static string GenerateAutomaticMail {
            get {
                return ResourceManager.GetString("GenerateAutomaticMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generuj bony.
        /// </summary>
        public static string GenerateVouchers {
            get {
                return ResourceManager.GetString("GenerateVouchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukryj progres.
        /// </summary>
        public static string HideProgress {
            get {
                return ResourceManager.GetString("HideProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duża.
        /// </summary>
        public static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatni raz uruchomiono: .
        /// </summary>
        public static string LastRunDate {
            get {
                return ResourceManager.GetString("LastRunDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powiązane elementy.
        /// </summary>
        public static string LinkedOrders {
            get {
                return ResourceManager.GetString("LinkedOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powiąż zamówienie.
        /// </summary>
        public static string LinkOrder {
            get {
                return ResourceManager.GetString("LinkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linki.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Załaduj obrazek.
        /// </summary>
        public static string LoadImage {
            get {
                return ResourceManager.GetString("LoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Załaduj skrypt SQL.
        /// </summary>
        public static string LoadSQLScript {
            get {
                return ResourceManager.GetString("LoadSQLScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane logowania.
        /// </summary>
        public static string LoginData {
            get {
                return ResourceManager.GetString("LoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treść wiadomości.
        /// </summary>
        public static string MailContent {
            get {
                return ResourceManager.GetString("MailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tworzenie wiadomości.
        /// </summary>
        public static string MailCreation {
            get {
                return ResourceManager.GetString("MailCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od: {0}.
        /// </summary>
        public static string MailFrom {
            get {
                return ResourceManager.GetString("MailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do: {0}.
        /// </summary>
        public static string MailTo {
            get {
                return ResourceManager.GetString("MailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogląd wiadomości.
        /// </summary>
        public static string MailView {
            get {
                return ResourceManager.GetString("MailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Złóż rezygnację.
        /// </summary>
        public static string MakeComplaint {
            get {
                return ResourceManager.GetString("MakeComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Złożenie zamówienia.
        /// </summary>
        public static string MakeOrder {
            get {
                return ResourceManager.GetString("MakeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje reklamacje.
        /// </summary>
        public static string MyComplaints {
            get {
                return ResourceManager.GetString("MyComplaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje zamówienia.
        /// </summary>
        public static string MyOrders {
            get {
                return ResourceManager.GetString("MyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota netto.
        /// </summary>
        public static string Netto {
            get {
                return ResourceManager.GetString("Netto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tylko zamówione.
        /// </summary>
        public static string OnlyOrder {
            get {
                return ResourceManager.GetString("OnlyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tylko wysłane.
        /// </summary>
        public static string OnlySent {
            get {
                return ResourceManager.GetString("OnlySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data otwarcia.
        /// </summary>
        public static string OpenDate {
            get {
                return ResourceManager.GetString("OpenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer przesyłki: .
        /// </summary>
        public static string ParcelNumber {
            get {
                return ResourceManager.GetString("ParcelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozmiar przesyłki.
        /// </summary>
        public static string ParcelSize {
            get {
                return ResourceManager.GetString("ParcelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metody płatności.
        /// </summary>
        public static string PayType {
            get {
                return ResourceManager.GetString("PayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena od:.
        /// </summary>
        public static string PriceFrom {
            get {
                return ResourceManager.GetString("PriceFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena netto.
        /// </summary>
        public static string PriceNetto {
            get {
                return ResourceManager.GetString("PriceNetto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cend do:.
        /// </summary>
        public static string PriceTo {
            get {
                return ResourceManager.GetString("PriceTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa procedury.
        /// </summary>
        public static string ProcedureName {
            get {
                return ResourceManager.GetString("ProcedureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tworzenie procesów.
        /// </summary>
        public static string ProcessCreation {
            get {
                return ResourceManager.GetString("ProcessCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość produktu.
        /// </summary>
        public static string ProductAmount {
            get {
                return ResourceManager.GetString("ProductAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie leków.
        /// </summary>
        public static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tylko do odczytu.
        /// </summary>
        public static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiadomości odebrane.
        /// </summary>
        public static string ReceivedMails {
            get {
                return ResourceManager.GetString("ReceivedMails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odbiorca.
        /// </summary>
        public static string Receiver {
            get {
                return ResourceManager.GetString("Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń również reklamacje z tego folderu.
        /// </summary>
        public static string RemoveAlsoFromThisFolder {
            get {
                return ResourceManager.GetString("RemoveAlsoFromThisFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń folder.
        /// </summary>
        public static string RemoveFolder {
            get {
                return ResourceManager.GetString("RemoveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przenieś reklamacje do folderu nadrzędnego.
        /// </summary>
        public static string RemoveToParentCatalog {
            get {
                return ResourceManager.GetString("RemoveToParentCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedz.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruchom wybrane procesy.
        /// </summary>
        public static string RunProcesses {
            get {
                return ResourceManager.GetString("RunProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaznacz wszystkie.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz bon.
        /// </summary>
        public static string SelectBon {
            get {
                return ResourceManager.GetString("SelectBon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz zamówienie.
        /// </summary>
        public static string SelectOrder {
            get {
                return ResourceManager.GetString("SelectOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz katalog nadrzędzny.
        /// </summary>
        public static string SelectParentFolder {
            get {
                return ResourceManager.GetString("SelectParentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz status.
        /// </summary>
        public static string SelectState {
            get {
                return ResourceManager.GetString("SelectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadawca.
        /// </summary>
        public static string Seller {
            get {
                return ResourceManager.GetString("Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesy sprzedawcy.
        /// </summary>
        public static string SellerProcesses {
            get {
                return ResourceManager.GetString("SellerProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij automatyczną wiadomość.
        /// </summary>
        public static string SendAutomaticEmail {
            get {
                return ResourceManager.GetString("SendAutomaticEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadawanie przesyłki.
        /// </summary>
        public static string SendCreation {
            get {
                return ResourceManager.GetString("SendCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysłane elementy.
        /// </summary>
        public static string SendElements {
            get {
                return ResourceManager.GetString("SendElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij wiadomość.
        /// </summary>
        public static string SendMail {
            get {
                return ResourceManager.GetString("SendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij wiadomość.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij wiadomość.
        /// </summary>
        public static string SendMessageAction {
            get {
                return ResourceManager.GetString("SendMessageAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elementy zamówione i wysłane.
        /// </summary>
        public static string SentAndOrderElements {
            get {
                return ResourceManager.GetString("SentAndOrderElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiadomości wysłane.
        /// </summary>
        public static string SentMails {
            get {
                return ResourceManager.GetString("SentMails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustaw ilość dni do odbioru.
        /// </summary>
        public static string SetPickupDays {
            get {
                return ResourceManager.GetString("SetPickupDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż elementy.
        /// </summary>
        public static string ShowElements {
            get {
                return ResourceManager.GetString("ShowElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż progres.
        /// </summary>
        public static string ShowProgress {
            get {
                return ResourceManager.GetString("ShowProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bon: {0}.
        /// </summary>
        public static string SingleVoucher {
            get {
                return ResourceManager.GetString("SingleVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mała.
        /// </summary>
        public static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortowanie.
        /// </summary>
        public static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suma.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podsumowanie.
        /// </summary>
        public static string Summarize {
            get {
                return ResourceManager.GetString("Summarize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP.
        /// </summary>
        public static string TIN {
            get {
                return ResourceManager.GetString("TIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temat.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do edycji.
        /// </summary>
        public static string ToEdit {
            get {
                return ResourceManager.GetString("ToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking przesyłek.
        /// </summary>
        public static string Tracking {
            get {
                return ResourceManager.GetString("Tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieokreślona data.
        /// </summary>
        public static string UndefinedDate {
            get {
                return ResourceManager.GetString("UndefinedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończ reklamację.
        /// </summary>
        public static string UndoComplaint {
            get {
                return ResourceManager.GetString("UndoComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        public static string VAT {
            get {
                return ResourceManager.GetString("VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bony.
        /// </summary>
        public static string Voucher {
            get {
                return ResourceManager.GetString("Voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generowanie bonów.
        /// </summary>
        public static string VoucherGeneration {
            get {
                return ResourceManager.GetString("VoucherGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waga.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
