name: CI

on:
  push:
    branches: [ "master" ] #wykonywany po kazdym push do mastera
  pull_request:
    branches: [ "master" ] #wykonywany na kazdym PR do mastera

  workflow_dispatch:

jobs: # joby
  build: # job - build
    runs-on: windows-latest # na jakiej maszynie uruchamiamy
    steps: 
      - uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.6
      - name: Restore NuGet's
        run: nuget restore OrderTrackingSystem.sln
      - name: Build OrderTrackingSystem App
        run: msbuild OrderTrackingSystem.sln
      
